### ISSUE TITLE
using version: latest in the sauceConnectOpts fails with a file error

### ISSUE THREAD

**Issue by christian-bromann** [bermi/sauce-connect-launcher#128]
```
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.
Downloading 7.16MB
Checksum check for manually overwritten sc version isn't supported.
Unzipping /Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/sc/sc-latest-osx.zip
Removing /Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/sc/sc-latest-osx.zip
Sauce Connect downloaded correctly
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.
Downloading 7.16MB
Checksum check for manually overwritten sc version isn't supported.
Unzipping /Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/sc/sc-latest-osx.zip
Removing /Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/sc/sc-latest-osx.zip
Sauce Connect downloaded correctly
A service failed in the 'onPrepare' hook
Error: Couldn't read sc permissions: ENOENT: no such file or directory, stat '/Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/sc/sc-latest-osx/bin/sc'
    at /Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:125:34
    at FSReqWrap.oncomplete (fs.js:114:15)

Continue...
ERROR: Couldn't connect to selenium server
chrome
Error
```

Looks like it's trygin to look in the `sc-latest-osx` directory, but it doesn't exist; only `sc-4.4.5-osx` does.

**Comment by johanneswuerbach** [comment]
Seems like a bug. Why do you specify `latest` explicitly? It should is the default when you don't specify a version.

**Comment by christian-bromann** [comment]
@johanneswuerbach I actually only copied the issue from `webdriverio/wdio-sauce-service` 🙈 . You have a good point there. I guess the actual issue then is to have a check if the provided version is available. So `latest` as version should not be valid. Only a version of the format `X.X.X`. Also having a note somewhere that states that always the latest SC version will be downloaded would help prevent issues like that. I leave this up to you.

Thanks for maintaining this project 👍

**Comment by nwwells** [comment]
I'm the one that filed the original issue in webdriverio/wdio-sauce-service.

I have to customize the connect config for my project and my process for doing so is always to just copy an example (which is helpfully provided in your README) and start messing with values. Unfortunately it broke, which was unexpected.
