### ISSUE TITLE
Invalid response status: 404

### ISSUE THREAD

**Issue by riderx** [bermi/sauce-connect-launcher#132]
since today i got this error, i don't know why, i have try with these export
```
export SAUCE_CONNECT_VERSION="4.4.7"
export SAUCE_CONNECT_VERSION="4.4.8"
export SAUCE_CONNECT_VERSION="latest"
```
but i get all time this error
```
Error: Download failed with status code: 404
    at ClientRequest.<anonymous> (/Users/martindonadieu/Project/toucantoco/Lark/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:219:23)
    at emitOne (events.js:120:20)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:564:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:453:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
```

**Comment by riderx** [comment]
okay i got the problem i was using read to export and the quote where put in the global so '"4.4.7"' is not a supported version
