### ISSUE TITLE
Error On Linux box , unable to launch sauce connect 

### ISSUE THREAD

**Issue by jagannath13** [bermi/sauce-connect-launcher#135]
node_modules/sauce-connect-launcher/sc/sc-4.4.10-linux/bin/sc ENOENT
11:07:43
    at exports._errnoException (util.js:1036:11)
11:07:43
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
11:07:43
    at onErrorNT (internal/child_process.js:359:16)
11:07:43
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
11:07:43
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by harshitushwahajec** [comment]
Having the same issue. Is there a fix?

**Comment by harshitushwahajec** [comment]
Got the solution! Use a Debian based Linux box or Docker image. It worked for me

**Comment by froucher** [comment]
Same issue for me, my base docker image is 'node:8-alpine'.

```sh
2020-02-07T12:44:58.350Z DEBUG @wdio/sauce-service: Opening local tunnel using Sauce Connect
2020-02-07T12:44:58.373Z DEBUG @wdio/sauce-service: Starting sc with args: -u XXXXXXXX -k XXXXXXXX --readyfile /tmp/sc-launcher-readyfile -x https://saucelabs.com/rest/v1
2020-02-07T12:44:58.403Z DEBUG @wdio/sauce-service: Sauce connect process errored: Error: spawn /app/node_modules/sauce-connect-launcher/sc/sc-4.5.4-linux/bin/sc ENOENT
2020-02-07T12:44:58.414Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: spawn /app/node_modules/sauce-connect-launcher/sc/sc-4.5.4-linux/bin/sc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Continue...
```

And I just use 'sauce' service

```js
  config: {
    user: process.env.SAUCELABS_USER,
    key: process.env.SAUCELABS_KEY,
    region: 'us',
    services: [ 'sauce' ],
    sauceConnect: true
  }
```

But it is just a confusing message, because it continues and test finishes right...

Thanks.

**Comment by harshitushwahajec** [comment]
> Same issue for me, my base docker image is 'node:8-alpine'.
> 
> ```shell
> 2020-02-07T12:44:58.350Z DEBUG @wdio/sauce-service: Opening local tunnel using Sauce Connect
> 2020-02-07T12:44:58.373Z DEBUG @wdio/sauce-service: Starting sc with args: -u XXXXXXXX -k XXXXXXXX --readyfile /tmp/sc-launcher-readyfile -x https://saucelabs.com/rest/v1
> 2020-02-07T12:44:58.403Z DEBUG @wdio/sauce-service: Sauce connect process errored: Error: spawn /app/node_modules/sauce-connect-launcher/sc/sc-4.5.4-linux/bin/sc ENOENT
> 2020-02-07T12:44:58.414Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
> Error: spawn /app/node_modules/sauce-connect-launcher/sc/sc-4.5.4-linux/bin/sc ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
>     at onErrorNT (internal/child_process.js:362:16)
>     at _combinedTickCallback (internal/process/next_tick.js:139:11)
>     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
>     at Function.Module.runMain (module.js:696:11)
>     at startup (bootstrap_node.js:204:16)
>     at bootstrap_node.js:625:3
> 
> Continue...
> ```
> 
> And I just use 'sauce' service
> 
> ```js
>   config: {
>     user: process.env.SAUCELABS_USER,
>     key: process.env.SAUCELABS_KEY,
>     region: 'us',
>     services: [ 'sauce' ],
>     sauceConnect: true
>   }
> ```
> 
> But it is just a confusing message, because it continues and test finishes right...
> 
> Thanks.

Try 
FROM node:8
in your dockerfile instead of FROM node:8-alpine.. It will pull the Debian based image by default and should work fine
